### ISSUE TITLE
RFC Refactoring

### ISSUE THREAD

**Issue by bowrocker** [basho/riak_test#667]
# Introduction

Refactoring relating to the rfc here:

https://gist.github.com/kellymclaughlin/f28b75ac295b3d397ef0
# Work Items
- [x] Refactor and break up rt module into appropriate subdomain functions (JA)
- [ ] Add specs to all rt\* functions and get them passing dialyzer
- [ ] Uniform naming for all rt modules
- [x] Create a harness behavior and have  each harness implement it (JA)
- [ ] Better integration points for Riak CS: backends, node lists, etc.
- [x] Improve node/deploy cluster API (KM)
- [x] Write a module to hide the details of the rt_properties record (getter setter) (KM)
- [x] Versioning for the rt_properties record (KM)
- [x] Add enforcement of valid backend fields from RT properties
- [ ] Update all the 2i tests not to run with bit cask
- [ ] Convert all tests to new conventions
- [ ] Determine which tests are worth running as rolling upgrade tests
- [x] Type annotations so we can run test categories (JA)
- [ ] Concurrent test runnings
- [ ] Ability to change the logging verbosity of the framework logging and the nodes under test independently via the command line or the configuration file. (BH)
# Branch

https://github.com/basho/riak_test/compare/feature/decouple-cluster-setup
